### ISSUE TITLE
curveradius and range path.path methods nonexisting?

### ISSUE THREAD

**Issue by gitAlwin** [pyx-project/pyx#34]
I hope this is the right place for the question / issue I have, I apologize if it isn't (In that case, what would be the correct place?). 

I am currently learning PyX and going through the documentation. I can't however get the methods [path.path.curveradius](https://pyx-project.org/manual/path.html#path.path.curveradius) and [path.path.range](https://pyx-project.org/manual/path.html?highlight=range#path.path.range) to work. E.g. when I create an ```arc``` called ```pth```
```
pth = path.path(path.arc(0, 0, 1, 0, 120))
```
and ask for its range
```
pth.range()
```
an error is returned
```
AttributeError: 'path' object has no attribute 'range'
```
Similarly for asking the ```curveradius``` at the beginning of the path
```
pth.curveradius(0)
```
results in
```
'path' object has no attribute 'curveradius'
```
I've looked into the [source code of the path module path.py](https://github.com/pyx-project/pyx/blob/master/pyx/path.py) and couldn't find the methods though could find other methods listed in the documentation. 

Also, I noticed that in the release announcement op PyX 0.13 that ```curveradius``` has been removed from the ```normpath``` module. Could it be that the method has been removed in the past but that this change was not updated in the documentation?

Thank you in advance for an answer.

Alwin

**Comment by joerg-lehmann** [comment]
Thanks, Alwin, for reporting this. As you guessed correctly, this was a bug in the documentation.
