### ISSUE TITLE
pip installation fails 

### ISSUE THREAD

**Issue by dejanu** [pyx-project/pyx#4]
`pip install PyX` or `pip install PyX==0.13` even `pip install git+https://github.com/pyx-project/pyx.git@fc66c078727b02693b122ad346b9fa5472e06eb7` , also tried with `no-cache-dir`
fails to install package and returns `No files/directories in /tmp/pip-build-cXIeQt/PyX/pip-egg-info (from PKG-INFO)`  the latest version I can install is pyX==0.12

**Comment by wobsta** [comment]
Are you aware of the fact, that PyX up to 0.12 is Python 2 only and starting from the PyX releases 0.13 we switched to Python 3 only? You cannot install PyX versions below 0.13 on Python 3 and PyX versions above 0.12 on Python 2.
