### ISSUE TITLE
Can PyX implement marks?

### ISSUE THREAD

**Issue by user202729** [pyx-project/pyx#54]
In LaTeX, there is a feature `savepos` in `zref` that allows saving the absolute location of something on a page (needs another compilation pass).

Which allows implementing something like [How can I make arrow from parts of a formula in Asymptote? (or: measure the width of a label, get anchor around a label) - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/707398/how-can-i-make-arrow-from-parts-of-a-formula-in-asymptote-or-measure-the-widt?noredirect=1&lq=1) . 

Would the same thing be possible in PyX? (I think it should be possible by using the engine primitives and write to file etc. or just write to stdout and make PyX parse the output somehow)

**Comment by wobsta** [comment]
Are you aware of https://pyx-project.org/examples/text/marker.html

**Comment by user202729** [comment]
Ah, cool.
